pipeline {
    agent any

    stages {
        stage("Clone Code") {
            steps {
                echo "🔁 Cloning the code from GitHub..."
                git branch: "main", url: "https://github.com/dhruv-dosh/AnjularDocker.git"
            }
        }

        stage("Clean Old Containers & Images") {
            steps {
                echo "🧹 Removing old containers and images..."
                bat '''
                cd hello-app
                docker-compose down
                '''
            }
        }

        stage("Build Docker Image") {
            steps {
                echo "⚙️ Building Docker image..."
                bat '''
                cd hello-app
                docker-compose up --build -d
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Deployment successful! Application is running"
        }
        failure {
            echo "❌ Deployment failed! Check Jenkins logs for details."
        }
    }
}
